<a href="https://colab.research.google.com/github/Tdeflash12/AI-ML/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
# string
country = ['India','Pakistan','USA','Nepal','Srilanka,Bhutan']

pd.Series(country)

0              India
1           Pakistan
2                USA
3              Nepal
4    Srilanka,Bhutan
dtype: object

In [8]:
# integers
runs = [13,24,56,78,100]

pd.Series(runs)

0     13
1     24
2     56
3     78
4    100
dtype: int64

In [10]:
# custom index
marks = [67,57,89,100]
subjects = ['maths','english','science','hindi']

pd.Series(marks,index=subjects)

maths       67
english     57
science     89
hindi      100
dtype: int64

In [12]:
# setting a game
marks=pd.Series(marks,index=subjects,name="Abhesh Marks")

In [13]:
marks

maths       67
english     57
science     89
hindi      100
Name: Abhesh Marks, dtype: int64

In [15]:
marks = {
    'maths':67,
    'english':57,
    'science':89,
    'hindi':100,
    'computer':100
}

marks_series = pd.Series(marks,name='Abhesh Marks')
marks_series

maths        67
english      57
science      89
hindi       100
computer    100
Name: Abhesh Marks, dtype: int64

In [16]:
# size
marks_series.size

5

In [17]:
marks_series.dtype

dtype('int64')

In [18]:
#name
marks_series.name

'Abhesh Marks'

In [19]:
# is_unique
marks_series.is_unique

False

In [22]:
#index
marks_series.index

Index(['maths', 'english', 'science', 'hindi', 'computer'], dtype='object')

In [24]:
# values
marks_series.values

numpy.ndarray

In [49]:
subs = pd.read_csv('/content/subs.csv').squeeze("columns")
subs

0       48
1       57
2       40
3       43
4       44
      ...
360    231
361    226
362    155
363    144
364    172
Name: Subscribers gained, Length: 365, dtype: int64

In [47]:
# with 2 cols
vkl = pd.read_csv('/content/kohli_ipl.csv', index_col='match_no')
vkl

          runs
match_no
1            1
2           23
3           13
4           12
5            1
...        ...
211          0
212         20
213         73
214         25
215          7

[215 rows x 1 columns]

In [54]:
movies = pd.read_csv('/content/bollywood.csv', index_col='movie').squeeze("columns")
movies

movie
Uri: The Surgical Strike                   Vicky Kaushal
Battalion 609                                Vicky Ahuja
The Accidental Prime Minister (film)         Anupam Kher
Why Cheat India                            Emraan Hashmi
Evening Shadows                         Mona Ambegaonkar
                                              ...
Hum Tumhare Hain Sanam                    Shah Rukh Khan
Aankhen (2002 film)                     Amitabh Bachchan
Saathiya (film)                             Vivek Oberoi
Company (film)                                Ajay Devgn
Awara Paagal Deewana                        Akshay Kumar
Name: lead, Length: 1500, dtype: object

In [55]:
#head and tail
subs.head()

0    48
1    57
2    40
3    43
4    44
Name: Subscribers gained, dtype: int64

In [58]:
vkl.head(6)

          runs
match_no
1            1
2           23
3           13
4           12
5            1
6            9

In [60]:
vkl.tail(15)

          runs
match_no
201         12
202          5
203         48
204          1
205         12
206          0
207          0
208          9
209         58
210         30
211          0
212         20
213         73
214         25
215          7

In [66]:
#sample // select random
movies.sample(4)

movie
Dream Girl (2019 film)         Ayushmann Khurrana
Pehchaan: The Face of Truth          Vinod Khanna
The Last Lear                    Amitabh Bachchan
Saas Bahu Aur Sensex                   Kiron Kher
Name: lead, dtype: object

In [67]:
#value_counts >> movies
movies.value_counts()

lead
Akshay Kumar         48
Amitabh Bachchan     45
Ajay Devgn           38
Salman Khan          31
Sanjay Dutt          26
                     ..
Seema Azmi            1
Akanksha Puri         1
Charanpreet Insan     1
Jaideep Ahlawat       1
Monali Thakur         1
Name: count, Length: 566, dtype: int64

In [76]:
# sort_values >>Inplace
vkl.sort_values(ascending=False).head(1).values[0]

np.int64(113)

In [79]:
vkl = vkl.copy()
vkl.sort_values(inplace=True)
vkl

match_no
8        0
87       0
93       0
91       0
206      0
      ...
164    100
120    100
123    108
126    109
128    113
Name: runs, Length: 215, dtype: int64

In [81]:
movies

movie
Uri: The Surgical Strike                   Vicky Kaushal
Battalion 609                                Vicky Ahuja
The Accidental Prime Minister (film)         Anupam Kher
Why Cheat India                            Emraan Hashmi
Evening Shadows                         Mona Ambegaonkar
                                              ...
Hum Tumhare Hain Sanam                    Shah Rukh Khan
Aankhen (2002 film)                     Amitabh Bachchan
Saathiya (film)                             Vivek Oberoi
Company (film)                                Ajay Devgn
Awara Paagal Deewana                        Akshay Kumar
Name: lead, Length: 1500, dtype: object

In [85]:
# sort_index -> inplace -> movies
movies.sort_index(ascending=False,inplace=True)
movies

movie
Zor Lagaa Ke...Haiya!            Meghan Jadhav
Zokkomon                       Darsheel Safary
Zindagi Tere Naam           Mithun Chakraborty
Zindagi Na Milegi Dobara        Hrithik Roshan
Zindagi 50-50                      Veena Malik
                                   ...
2 States (2014 film)              Arjun Kapoor
1971 (2007 film)                Manoj Bajpayee
1920: The Evil Returns             Vicky Ahuja
1920: London                     Sharman Joshi
1920 (film)                   Rajniesh Duggall
Name: lead, Length: 1500, dtype: object

In [88]:
vkl.sort_values(inplace=True)
vkl

match_no
8        0
87       0
93       0
91       0
206      0
      ...
164    100
120    100
123    108
126    109
128    113
Name: runs, Length: 215, dtype: int64

In [89]:
vkl.count()

np.int64(215)